# Server
server.port=8080

# Database
spring.datasource.url=jdbc:mysql://roundhouse.proxy.rlwy.net:22581/railway
spring.datasource.username=root
spring.datasource.password=YTBMKLXubzOUJPLaCkxRxpjRQJptQEmn
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# App
spring.application.name=skilldrop-backen

jwt.secret=qWmZrTnXbAplKcYdHsUeFvJoIgRkLxBt
jwt.expiration=900000

stripe.secret-key=sk_test_51TL74dPVIKjpGwDFtffqjzFtkZztGDtranvkdmi1AZVzdrjz8mvKfaCMihByrUSsNB7HYQAxfCInCkq1Hx4YOwoL0043fDT87Z
stripe.webhook-secret=

cloudflare.r2.access-key=7446ba6a9501be3f09b246f33f56f1b0
cloudflare.r2.secret-key=8399ff4333f72dbc017fc8ae5b970836edccfe461fc5cd51ff6877c388fbd58b
cloudflare.r2.endpoint=https://51dd81b3de661bd4dfccf07da2213b0f.r2.cloudflarestorage.com/skilldrop
cloudflare.r2.bucket=skilldrop

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

resend.api-key=re_aNjVBYs1_2MCRXpmJaY9ewvitovypYPcy

